# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: mysql2
  database: facebook_database
  socket: /opt/lampp/var/mysql/mysql.sock
  timeout: 5000
  username: root
  password: 